project:
  type: website
  output-dir: docs

website:
  title: "Carl Gaspar"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SourCherries
      - icon: twitter
        href: https://twitter.com/carl_m_gaspar
format:
  html:
    theme: litera # litera, united, cosmo
    css: styles.css

editor: visual

website:
  twitter-card: true